---
- hosts: all
  tasks:
  - name: include airspaces
    include_vars: vars/airspaces.yml

  - name: prepare nginx config
    become: yes
    template:
      src: templates/nginx_conf.j2
      dest: /etc/nginx/sites-available/{{ item.name }}.airspaces.conf
    with_items: "{{ airspaces }}"

  - name: link nginx config
    become: yes
    file:
      src: /etc/nginx/sites-available/{{ item.name }}.airspaces.conf
      dest: /etc/nginx/sites-enabled/{{ item.name }}.airspaces.conf
    with_items: "{{ airspaces }}"

  - name: reload nginx
    become: yes
    service:
      name: nginx
      state: reloaded

  - name: make sure dockers are running
    docker_container:
      name: "airspace_{{ item.name }}"
      image: foucdeg/airspaces:latest
      state: started
      ports:
        - "{{ item.web_port }}:9000"
        - "{{ item.udp_port }}:49003/udp"
    with_items: "{{ airspaces }}"
